/**
 * Feature Flags Configuration
 * Controls which features are enabled/disabled in the application
 */

export interface FeatureFlag {
  enabled: boolean;
  name: string;
  description: string;
  development?: boolean;
  disclaimer?: string;
}

export const FEATURE_FLAGS: Record<string, FeatureFlag> = {
  // AI Features
  ama: {
    enabled: true,
    name: 'Ask Me Anything (AMA)',
    description: 'AI-powered Q&A feature for portfolio inquiries',
    development: true,
    disclaimer: '🚧 This feature is under development. Results may not be optimal and responses are generated by AI.'
  },

  qa: {
    enabled: true,
    name: 'CV Question Answering',
    description: 'AI-powered CV content analysis and Q&A',
    development: true,
    disclaimer: '⚠️ This feature is in development. The AI responses may not be as accurate as expected.'
  },

  // Document Features
  documentViewer: {
    enabled: true,
    name: 'Document Viewer',
    description: 'Interactive document viewing with PDF and image support',
    development: false
  },

  // Navigation Features
  homeButton: {
    enabled: true,
    name: 'Home Button',
    description: 'Navigation home button in document viewer',
    development: false
  },

  // PDF Features
  pdfGeneration: {
    enabled: true,
    name: 'PDF Generation',
    description: 'Automatic CV PDF generation',
    development: false
  }
};

/**
 * Check if a feature is enabled
 */
export const isFeatureEnabled = (featureKey: keyof typeof FEATURE_FLAGS): boolean => {
  return FEATURE_FLAGS[featureKey]?.enabled ?? false;
};

/**
 * Check if a feature is in development
 */
export const isFeatureInDevelopment = (featureKey: keyof typeof FEATURE_FLAGS): boolean => {
  return FEATURE_FLAGS[featureKey]?.development ?? false;
};

/**
 * Get feature disclaimer message
 */
export const getFeatureDisclaimer = (featureKey: keyof typeof FEATURE_FLAGS): string | undefined => {
  return FEATURE_FLAGS[featureKey]?.disclaimer;
};

/**
 * Get all enabled features
 */
export const getEnabledFeatures = (): Record<string, FeatureFlag> => {
  return Object.fromEntries(
    Object.entries(FEATURE_FLAGS).filter(([_, flag]) => flag.enabled)
  );
};

/**
 * Get all features in development
 */
export const getDevelopmentFeatures = (): Record<string, FeatureFlag> => {
  return Object.fromEntries(
    Object.entries(FEATURE_FLAGS).filter(([_, flag]) => flag.development)
  );
};